BOARD_TAG = nano328
ARDUINO_PORT = /dev/ttyUSB0
#ARDUINO_LIBS = /usr/share/arudino/libraries
ARDUINO_DIR = /usr/share/arduino
#ARDMK_DIR = /usr/bin
#AVR_TOOLS_DIR =/usr/share/arduino/hardware/tools

include /usr/share/arduino/Arduino.mk